### ISSUE TITLE
It seems 'moviepy' isn't installed

### ISSUE THREAD

**Issue by ZahraAdahman** [cellistigs/carcealab_videoconfig#6]
![moviepy_not_installed](https://user-images.githubusercontent.com/59964869/101478561-e04ee100-391e-11eb-8785-307f8bff029e.PNG)

**Comment by cellistigs** [comment]
Hi- Not sure from the look of this console but it looks like you're still in the "main" conda environment. Moviepy should be installed in the "carcealab_videoconfig" environment, which you can activate by running `source activate carcealab_videoconfig`. I'm going to close this issue- please open another if this is still a problem.
