### ISSUE TITLE
Numpy_runtime_bug on windows Git bash

### ISSUE THREAD

**Issue by ZahraAdahman** [cellistigs/carcealab_videoconfig#7]
Running checkconfig.py script, was stopped by a runtime error.
See image below: 

![numpy_runtime_bug](https://user-images.githubusercontent.com/59964869/101479717-a7177080-3920-11eb-80c7-a714b5e674aa.PNG)

**Comment by cellistigs** [comment]
This looks like a scary issue, but I think that this should also be taken care of by working inside the correct conda environment. Please try running again in `carcealab_videoconfig`- I expect this will take care of the issue. Once again, if it doesn't please open a new issue, and feel free to reference these (as #6 and #7) to save some space.
